// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy715AlefQ9kHltT_cQOIKz1xjYfUj9L4',
    appId: '1:183059140308:web:916d0b92b27f5246797541',
    messagingSenderId: '183059140308',
    projectId: 'ticker-ed091',
    authDomain: 'ticker-ed091.firebaseapp.com',
    storageBucket: 'ticker-ed091.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKQpSHV3MfJYrgWjI5ju1dEJIXtBSOY2E',
    appId: '1:183059140308:android:e6ae1ce3c1f28055797541',
    messagingSenderId: '183059140308',
    projectId: 'ticker-ed091',
    storageBucket: 'ticker-ed091.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX7PObdolhDSavvi9iCmd6LV8wpYI-l2c',
    appId: '1:183059140308:ios:401746efcbfc7a7e797541',
    messagingSenderId: '183059140308',
    projectId: 'ticker-ed091',
    storageBucket: 'ticker-ed091.firebasestorage.app',
    iosBundleId: 'com.example.ticker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX7PObdolhDSavvi9iCmd6LV8wpYI-l2c',
    appId: '1:183059140308:ios:401746efcbfc7a7e797541',
    messagingSenderId: '183059140308',
    projectId: 'ticker-ed091',
    storageBucket: 'ticker-ed091.firebasestorage.app',
    iosBundleId: 'com.example.ticker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy715AlefQ9kHltT_cQOIKz1xjYfUj9L4',
    appId: '1:183059140308:web:ffe23c56600f51f5797541',
    messagingSenderId: '183059140308',
    projectId: 'ticker-ed091',
    authDomain: 'ticker-ed091.firebaseapp.com',
    storageBucket: 'ticker-ed091.firebasestorage.app',
  );
}
